OPENAI_API_KEY="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"
GROQ_API_KEY="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"
NEWS_API_KEY="abd29d5652914c009f8d43bd4792dce7"